In [1]:
import torch

In [2]:
# 示例：创建 3x4 的网格
y = torch.arange(3)  # [0, 1, 2]
x = torch.arange(4)  # [0, 1, 2, 3]

yy, xx = torch.meshgrid(y, x, indexing='ij')
print("indexing='ij':")
print("yy (y坐标):")
print(yy)
print("xx (x坐标):")
print(xx)

indexing='ij':
yy (y坐标):
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]])
xx (x坐标):
tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])


In [3]:
# 示例：创建 3x4 的网格
y = torch.arange(3)  # [0, 1, 2]
x = torch.arange(4)  # [0, 1, 2, 3]

yy, xx = torch.meshgrid(y, x, indexing='xy')
print("indexing='ij':")
print("yy (y坐标):")
print(yy)
print("xx (x坐标):")
print(xx)

indexing='ij':
yy (y坐标):
tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])
xx (x坐标):
tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


In [5]:
dims = (5, 5)
y, x = torch.meshgrid(torch.arange(dims[0]), torch.arange(dims[1]), indexing='ij')
grid = torch.stack([y.flatten(), x.flatten()], dim=1).unsqueeze(0)
print(grid)

tensor([[[0, 0],
         [0, 1],
         [0, 2],
         [0, 3],
         [0, 4],
         [1, 0],
         [1, 1],
         [1, 2],
         [1, 3],
         [1, 4],
         [2, 0],
         [2, 1],
         [2, 2],
         [2, 3],
         [2, 4],
         [3, 0],
         [3, 1],
         [3, 2],
         [3, 3],
         [3, 4],
         [4, 0],
         [4, 1],
         [4, 2],
         [4, 3],
         [4, 4]]])


In [6]:
grid = grid / (torch.tensor(dims, ).unsqueeze(0).unsqueeze(0) - 1)
print(grid)


tensor([[[0.0000, 0.0000],
         [0.0000, 0.2500],
         [0.0000, 0.5000],
         [0.0000, 0.7500],
         [0.0000, 1.0000],
         [0.2500, 0.0000],
         [0.2500, 0.2500],
         [0.2500, 0.5000],
         [0.2500, 0.7500],
         [0.2500, 1.0000],
         [0.5000, 0.0000],
         [0.5000, 0.2500],
         [0.5000, 0.5000],
         [0.5000, 0.7500],
         [0.5000, 1.0000],
         [0.7500, 0.0000],
         [0.7500, 0.2500],
         [0.7500, 0.5000],
         [0.7500, 0.7500],
         [0.7500, 1.0000],
         [1.0000, 0.0000],
         [1.0000, 0.2500],
         [1.0000, 0.5000],
         [1.0000, 0.7500],
         [1.0000, 1.0000]]])
